	candy_gw_qsys u0 (
		.adc_export                        (<connected-to-adc_export>),                        //                         adc.export
		.altpll_locked_export              (<connected-to-altpll_locked_export>),              //               altpll_locked.export
		.clk_clk                           (<connected-to-clk_clk>),                           //                         clk.clk
		.codec_clk_clk                     (<connected-to-codec_clk_clk>),                     //                   codec_clk.clk
		.codec_reset_export                (<connected-to-codec_reset_export>),                //                 codec_reset.export
		.grove1_in_port                    (<connected-to-grove1_in_port>),                    //                      grove1.in_port
		.grove1_out_port                   (<connected-to-grove1_out_port>),                   //                            .out_port
		.i2s_lrclk_i_mst                   (<connected-to-i2s_lrclk_i_mst>),                   //                         i2s.lrclk_i_mst
		.i2s_data_i_mst                    (<connected-to-i2s_data_i_mst>),                    //                            .data_i_mst
		.i2s_data_o_mst                    (<connected-to-i2s_data_o_mst>),                    //                            .data_o_mst
		.i2s_lrclk_o_slv                   (<connected-to-i2s_lrclk_o_slv>),                   //                            .lrclk_o_slv
		.i2s_data_o_slv                    (<connected-to-i2s_data_o_slv>),                    //                            .data_o_slv
		.i2s_bitclk_o_slv                  (<connected-to-i2s_bitclk_o_slv>),                  //                            .bitclk_o_slv
		.new_sdram_controller_0_wire_addr  (<connected-to-new_sdram_controller_0_wire_addr>),  // new_sdram_controller_0_wire.addr
		.new_sdram_controller_0_wire_ba    (<connected-to-new_sdram_controller_0_wire_ba>),    //                            .ba
		.new_sdram_controller_0_wire_cas_n (<connected-to-new_sdram_controller_0_wire_cas_n>), //                            .cas_n
		.new_sdram_controller_0_wire_cke   (<connected-to-new_sdram_controller_0_wire_cke>),   //                            .cke
		.new_sdram_controller_0_wire_cs_n  (<connected-to-new_sdram_controller_0_wire_cs_n>),  //                            .cs_n
		.new_sdram_controller_0_wire_dq    (<connected-to-new_sdram_controller_0_wire_dq>),    //                            .dq
		.new_sdram_controller_0_wire_dqm   (<connected-to-new_sdram_controller_0_wire_dqm>),   //                            .dqm
		.new_sdram_controller_0_wire_ras_n (<connected-to-new_sdram_controller_0_wire_ras_n>), //                            .ras_n
		.new_sdram_controller_0_wire_we_n  (<connected-to-new_sdram_controller_0_wire_we_n>),  //                            .we_n
		.oe_export                         (<connected-to-oe_export>),                         //                          oe.export
		.onbrd_led_pwm_out                 (<connected-to-onbrd_led_pwm_out>),                 //                   onbrd_led.pwm_out
		.pmod2_export                      (<connected-to-pmod2_export>),                      //                       pmod2.export
		.qspi_dclk                         (<connected-to-qspi_dclk>),                         //                        qspi.dclk
		.qspi_ncs                          (<connected-to-qspi_ncs>),                          //                            .ncs
		.qspi_data                         (<connected-to-qspi_data>),                         //                            .data
		.reset_reset_n                     (<connected-to-reset_reset_n>),                     //                       reset.reset_n
		.sdclk_clk_clk                     (<connected-to-sdclk_clk_clk>),                     //                   sdclk_clk.clk
		.uart_rxd                          (<connected-to-uart_rxd>),                          //                        uart.rxd
		.uart_txd                          (<connected-to-uart_txd>),                          //                            .txd
		.uart_cts_n                        (<connected-to-uart_cts_n>),                        //                            .cts_n
		.uart_rts_n                        (<connected-to-uart_rts_n>),                        //                            .rts_n
		.wb_ack_i                          (<connected-to-wb_ack_i>),                          //                          wb.ack_i
		.wb_adr_o                          (<connected-to-wb_adr_o>),                          //                            .adr_o
		.wb_clk_o                          (<connected-to-wb_clk_o>),                          //                            .clk_o
		.wb_cyc_o                          (<connected-to-wb_cyc_o>),                          //                            .cyc_o
		.wb_dat_i                          (<connected-to-wb_dat_i>),                          //                            .dat_i
		.wb_dat_o                          (<connected-to-wb_dat_o>),                          //                            .dat_o
		.wb_err_i                          (<connected-to-wb_err_i>),                          //                            .err_i
		.wb_rst_o                          (<connected-to-wb_rst_o>),                          //                            .rst_o
		.wb_rty_i                          (<connected-to-wb_rty_i>),                          //                            .rty_i
		.wb_sel_o                          (<connected-to-wb_sel_o>),                          //                            .sel_o
		.wb_stb_o                          (<connected-to-wb_stb_o>),                          //                            .stb_o
		.wb_we_o                           (<connected-to-wb_we_o>),                           //                            .we_o
		.i2s_bclk_mst_clk                  (<connected-to-i2s_bclk_mst_clk>)                   //                i2s_bclk_mst.clk
	);

