# TCL File Generated by Component Editor 18.1
# Thu Jun 25 23:45:04 JST 2020
# DO NOT MODIFY


# 
# avalon_i2s "Avalon I2S Bridge" v0.1
# Shunichi Yamamoto 2020.06.25.23:45:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_i2s
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_i2s
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Shunichi Yamamoto"
set_module_property DISPLAY_NAME "Avalon I2S Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AVALON_I2S
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_i2s.vhd VHDL PATH avalon_i2s.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset csi_reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock clock
set_interface_property external_connection associatedReset reset
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection LRCLK_I_MST lrclk_i_mst Input 1
add_interface_port external_connection DATA_I_MST data_i_mst Input 1
add_interface_port external_connection DATA_O_MST data_o_mst Output 1
add_interface_port external_connection LRCLK_O_SLV lrclk_o_slv Output 1
add_interface_port external_connection DATA_O_SLV data_o_slv Output 1
add_interface_port external_connection BITCLK_O_SLV bitclk_o_slv Output 1


# 
# connection point av_mm2
# 
add_interface av_mm2 avalon start
set_interface_property av_mm2 addressUnits SYMBOLS
set_interface_property av_mm2 associatedClock clock
set_interface_property av_mm2 associatedReset reset
set_interface_property av_mm2 bitsPerSymbol 8
set_interface_property av_mm2 burstOnBurstBoundariesOnly false
set_interface_property av_mm2 burstcountUnits WORDS
set_interface_property av_mm2 doStreamReads false
set_interface_property av_mm2 doStreamWrites false
set_interface_property av_mm2 holdTime 0
set_interface_property av_mm2 linewrapBursts false
set_interface_property av_mm2 maximumPendingReadTransactions 0
set_interface_property av_mm2 maximumPendingWriteTransactions 0
set_interface_property av_mm2 readLatency 0
set_interface_property av_mm2 readWaitTime 1
set_interface_property av_mm2 setupTime 0
set_interface_property av_mm2 timingUnits Cycles
set_interface_property av_mm2 writeWaitTime 0
set_interface_property av_mm2 ENABLED true
set_interface_property av_mm2 EXPORT_OF ""
set_interface_property av_mm2 PORT_NAME_MAP ""
set_interface_property av_mm2 CMSIS_SVD_VARIABLES ""
set_interface_property av_mm2 SVD_ADDRESS_GROUP ""

add_interface_port av_mm2 av_mm2_address address Output 3
add_interface_port av_mm2 av_mm2_waitrequest waitrequest Input 1
add_interface_port av_mm2 av_mm2_read read Output 1
add_interface_port av_mm2 av_mm2_readdata readdata Input 32


# 
# connection point av_mm1
# 
add_interface av_mm1 avalon start
set_interface_property av_mm1 addressUnits SYMBOLS
set_interface_property av_mm1 associatedClock clock
set_interface_property av_mm1 associatedReset reset
set_interface_property av_mm1 bitsPerSymbol 8
set_interface_property av_mm1 burstOnBurstBoundariesOnly false
set_interface_property av_mm1 burstcountUnits WORDS
set_interface_property av_mm1 doStreamReads false
set_interface_property av_mm1 doStreamWrites false
set_interface_property av_mm1 holdTime 0
set_interface_property av_mm1 linewrapBursts false
set_interface_property av_mm1 maximumPendingReadTransactions 0
set_interface_property av_mm1 maximumPendingWriteTransactions 0
set_interface_property av_mm1 readLatency 0
set_interface_property av_mm1 readWaitTime 1
set_interface_property av_mm1 setupTime 0
set_interface_property av_mm1 timingUnits Cycles
set_interface_property av_mm1 writeWaitTime 0
set_interface_property av_mm1 ENABLED true
set_interface_property av_mm1 EXPORT_OF ""
set_interface_property av_mm1 PORT_NAME_MAP ""
set_interface_property av_mm1 CMSIS_SVD_VARIABLES ""
set_interface_property av_mm1 SVD_ADDRESS_GROUP ""

add_interface_port av_mm1 av_mm1_address address Output 3
add_interface_port av_mm1 av_mm1_write write Output 1
add_interface_port av_mm1 av_mm1_writedata writedata Output 32
add_interface_port av_mm1 av_mm1_waitrequest waitrequest Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock bit_clk_mst clk Input 1

