/*
 * File:           C:\Users\shun\Documents\QuartusPrimeProjects\CANDY_GW_10M16\SigmaDSP\adau1761_IC_1_PARAM.h
 *
 * Created:        Tuesday, June 23, 2020 11:37:21 PM
 * Description:    adau1761:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2020 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ADAU1761_IC_1_PARAM_H__
#define __ADAU1761_IC_1_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "IC1"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00001000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(4096)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module Single 1 - Single Volume Shared*/
#define MOD_SINGLE1_COUNT                              4
#define MOD_SINGLE1_DEVICE                             "IC1"
#define MOD_SINGLE1_ALG0_DATA_ADR_ADDR                 8
#define MOD_SINGLE1_ALG0_DATA_ADR_FIXPT                0x00000008
#define MOD_SINGLE1_ALG0_DATA_ADR_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_SINGLE1_ALG0_DATA_ADR_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLE1_ALG0_COEFF_ADR_ADDR                9
#define MOD_SINGLE1_ALG0_COEFF_ADR_FIXPT               0x0000000A
#define MOD_SINGLE1_ALG0_COEFF_ADR_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(10)
#define MOD_SINGLE1_ALG0_COEFF_ADR_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLE1_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE1_ADDR 10
#define MOD_SINGLE1_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE1_FIXPT 0x00040C37
#define MOD_SINGLE1_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0316227766016838)
#define MOD_SINGLE1_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE1_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE1_ADDR 11
#define MOD_SINGLE1_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE1_FIXPT 0x00001000
#define MOD_SINGLE1_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00048828125)
#define MOD_SINGLE1_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE1_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Single 1_2 - Single Volume Shared*/
#define MOD_SINGLE1_2_COUNT                            4
#define MOD_SINGLE1_2_DEVICE                           "IC1"
#define MOD_SINGLE1_2_ALG0_DATA_ADR_ADDR               13
#define MOD_SINGLE1_2_ALG0_DATA_ADR_FIXPT              0x00000010
#define MOD_SINGLE1_2_ALG0_DATA_ADR_VALUE              SIGMASTUDIOTYPE_INTEGER_CONVERT(16)
#define MOD_SINGLE1_2_ALG0_DATA_ADR_TYPE               SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLE1_2_ALG0_COEFF_ADR_ADDR              14
#define MOD_SINGLE1_2_ALG0_COEFF_ADR_FIXPT             0x0000000F
#define MOD_SINGLE1_2_ALG0_COEFF_ADR_VALUE             SIGMASTUDIOTYPE_INTEGER_CONVERT(15)
#define MOD_SINGLE1_2_ALG0_COEFF_ADR_TYPE              SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLE1_2_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE2_ADDR 15
#define MOD_SINGLE1_2_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE2_FIXPT 0x00287A26
#define MOD_SINGLE1_2_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.316227766016838)
#define MOD_SINGLE1_2_ALG0_TARGETGAINS200ALGGROWDBSTEPSUBROUTINE2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE1_2_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE2_ADDR 16
#define MOD_SINGLE1_2_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE2_FIXPT 0x00001000
#define MOD_SINGLE1_2_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00048828125)
#define MOD_SINGLE1_2_ALG0_APPROXFACTORGAINS200ALGGROWDBSTEPSUBROUTINE2_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
